#!/bin/sh

echo "Version to build:"
grep version package.json | sed 's/version//g; s/[":,]//g;'
echo

echo "Is this the right version number?"
echo "Did you commit all your changes?"
echo "Did you create a git tag?"
echo "Hit ENTER to continue!"
read

vsce package || exit 1

pushd python > /dev/null
rm -rf dist/
python3 -m build || exit 1
popd > /dev/null

echo
echo "Now upload the .vsix file to https://marketplace.visualstudio.com/manage/publishers/stefanwehr"
echo
echo "To upload the package to PyPI, execute the following command: twine upload python/dist/*"
