#!/bin/sh

echo "Did you increase the version number?"
echo "Did you commit all your changes?"
echo "Did you create a git tag?"
echo "Hit ENTER to continue!"
read

vsce package

echo
echo "Now upload the .vsix file to https://marketplace.visualstudio.com/manage/publishers/stefanwehr"
