#!/bin/bash

set -e

cd $(dirname $0)

function run()
{
    echo
    echo "Running tests for Python version $PYENV_VERSION"
    echo
    ./allTestsForPyVersion
    echo
    echo "Finished tests for Python version $PYENV_VERSION"
    echo
}

PYENV_VERSION=3.12 run
PYENV_VERSION=3.13 run
PYENV_VERSION=3.14 run
