#!/bin/bash

set -e
set -u

cd $(dirname $0)

unit_test_path=code/wypp:tests:code
integration_test_path=code/wypp:integration-tests:code

function usage()
{
    echo "USAGE: $0 [--unit | --integration] [ FILE ]"
    exit 1
}

function run_unit_tests()
{
   echo "Running unit tests, PYTHONPATH=$unit_test_path"
    if [ -z "${1:-}" ]; then
         PYTHONPATH=$unit_test_path python3 -m unittest tests/test*.py
        ecode=$?
    else
        PYTHONPATH=$unit_test_path python3 -m unittest "$@"
        ecode=$?
    fi
    echo "Done with unit tests"
}

function run_integration_tests()
{
    echo "Running all integration tests, PYTHONPATH=$integration_test_path"
    if [ -z "${1:-}" ]; then
        PYTHONPATH=$integration_test_path python3 -m unittest integration-tests/test*.py
        ecode=$?
    else
        PYTHONPATH=$integration_test_path python3 -m unittest "$@"
        ecode=$?
    fi
    echo "Done with integration tests"
}


echo "Python version:"
python3 --version

if [ -z "${1:-}" ]; then
    run_unit_tests
    echo
    run_integration_tests
    echo
    echo "Running file tests ..."
    python3 ./fileTests.py
elif [ "$1" == "--unit" ]; then
    shift
    run_unit_tests "$@"
    exit $ecode
elif [ "$1" == "--integration" ]; then
    shift
    run_integration_tests "$@"
    exit $ecode
else
    usage
fi

