from fileTestsLib import *

checkInstall('test-data/fileWithImport.py')
checkInstall('test-data/fileWithoutImport.py')
checkInstall('test-data/fileWithBothImports.py')
checkInstall('test-data/fileWithRecursiveTypes.py')
checkBoth('test-data/testTraceback.py')
checkBoth('test-data/testTraceback2.py')
checkBoth('test-data/testTraceback3.py')
checkBoth('test-data/testArgs.py', exitCode=0, args=['ARG_1', 'ARG_2'])
checkBoth('test-data/printModuleName.py', exitCode=0)
checkBoth('test-data/printModuleNameImport.py', exitCode=0)
checkBoth('test-data/testTypes1.py')
checkBoth('test-data/testIndexError.py')
checkBoth('test-data/testWrapperError.py')
checkBoth('test-data/testCheckFail.py', exitCode=0)
check('test-data/testTypes2.py', exitCode=1)
check('test-data/testTypes2.py', exitCode=0, typecheck=False)
check('test-data/testABCMeta.py')
check('test-data/testClassHierarchy.py', exitCode=0)
check('test-data/testTypesCollections1.py')
check('test-data/testTypesCollections2.py')
check('test-data/testTypesCollections3.py')
check('test-data/testTypesCollections4.py')
check('test-data/testTypesProtos1.py')
check('test-data/testTypesProtos2.py')
check('test-data/testTypesProtos3.py')
check('test-data/testTypesProtos4.py')
check('test-data/testTypesSubclassing1.py')
check('test-data/testTypesHigherOrderFuns.py')
check('test-data/testTypesHigherOrderFuns2.py', exitCode=0)
check('test-data/testTypesHigherOrderFuns3.py')
check('test-data/testTypesHigherOrderFuns4.py', exitCode=0)
check('test-data/testTypesHigherOrderFuns5.py', exitCode=0)
check('test-data/testTypesRecordInheritance.py')
check('test-data/testRecordSetTypes.py')
check('test-data/testRecordSetTypeForwardRef.py')
check('test-data/testForwardRef.py', exitCode=0)
check('test-data/testForwardRef1.py', exitCode=0)
check('test-data/testForwardRef2.py')
check('test-data/testForwardRef3.py', exitCode=0)
check('test-data/testForwardRef4.py')
check('test-data/testForwardRef5.py')
check('test-data/testForwardRef6.py', exitCode=0)
check('test-data/testHintParentheses1.py')
check('test-data/testHintParentheses2.py')
check('test-data/testHintParentheses3.py')
check('test-data/testTypesReturn.py')
check('test-data/testMissingReturn.py')
check('test-data/testTypesSequence1.py')
check('test-data/testTypesSequence2.py')
check('test-data/testTypesTuple1.py')
check('test-data/wrong-caused-by.py')
check('test-data/declared-at-missing.py')
check('test-data/testTypesSet1.py')
check('test-data/testTypesSet2.py')
check('test-data/testTypesSet3.py')
check('test-data/testTypesSet4.py')
check('test-data/testTypesDict1.py')
check('test-data/testTypesDict2.py')
check('test-data/testTypesDict3.py')
check('test-data/testTypesDict4.py')
check('test-data/testIterableImplicitAny.py')
check('test-data/testDoubleWrappingDicts.py', exitCode=0)
check('test-data/testClassRecursion.py', exitCode=0)
check('test-data/testWrongNumOfArguments.py')
check('test-data/testWrongNumOfArguments2.py')
check('test-data/testLiteralInstanceOf.py', exitCode=0)
check('test-data/testWrongKeywordArg.py')
check('test-data/testWrongKeywordArg2.py')
check('test-data/testComplex.py', exitCode=0)
check('test-data/testUnionLiteral.py', exitCode=0)
check('test-data/testCheck.py', exitCode=0)
check('test-data/testNameErrorBug.py', exitCode=0)
check('test-data/testOriginalTypeNames.py', exitCode=0)
check('test-data/testDeepEqBug.py', exitCode=0)
check('test-data/testLockFactory.py')
check('test-data/testLockFactory2.py')
check('test-data/testGetSource.py')
check('test-data/testDict.py', exitCode=0)
check('test-data/testFunEq.py', exitCode=0)
check('test-data/testBugSliceIndices.py', exitCode=0)
check('test-data/testABC.py', exitCode=0)
check('test-data/testTypesWrapperEq.py', exitCode=0)
check('test-data/testTypesProtos5.py', exitCode=0)
check('test-data/testTypesProtos6.py')
check('test-data/testTypesProtos7.py')
check('test-data/testTypesProtos8.py')
check('test-data/testTypesProtos9.py')
check('test-data/testIterable1.py', exitCode=0)
check('test-data/testIterable2.py', exitCode=0)
check('test-data/testIterable3.py', exitCode=0)
check('test-data/testIterable4.py', exitCode=0)
check('test-data/testIterable5.py', exitCode=0)
check('test-data/testIterable6.py', exitCode=0)
check('test-data/testIterable7.py')
check('test-data/testIterator.py', exitCode=0)
check('test-data/testIterator2.py', exitCode=0)
check('test-data/testIterator3.py', exitCode=0)
check('test-data/testIterator4.py', exitCode=0)
check('test-data/testConcat.py', exitCode=0)
check('test-data/testCopy.py', exitCode=0)
check('test-data/testHof.py', exitCode=0)
check('test-data/testIndexSeq.py', exitCode=0)
check('test-data/testWrap.py', exitCode=0)
check('test-data/testWrap2.py', exitCode=0)
check('test-data/testTodo.py')
check('test-data/testImpossible.py')
check('test-data/testInvalidLiteral.py')
check('test-data/admin.py', exitCode=0)
check('test-data/modules/A/main.py', args=['--extra-dir', 'test-data/modules/B'],
      pythonPath=['test-data/modules/B'])
check('test-data/testUnion.py', exitCode=0)
check('test-data/testUnion2.py', exitCode=0)
check('test-data/testUnion3.py', exitCode=0)
check('test-data/testLiteral1.py')
check('test-data/testForwardTypeInRecord.py', exitCode=0)
check('test-data/testForwardTypeInRecord2.py', exitCode=0)
check('test-data/testUnionOfUnion.py', exitCode=0)
check('test-data/testRecordTypes.py')
#check('test-data/testDisappearingObject_01.py', exitCode=0)
#check('test-data/testDisappearingObject_02.py', exitCode=0)
#check('test-data/testDisappearingObject_03.py', exitCode=0)
checkBoth('test-data/testTypeKeyword.py', exitCode=0, minVersion=(3,12))

globalCtx.results.finish()
