#!/bin/bash

if [ -z "$PY" ]; then
    PY=python3
fi
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

OPTS="--quiet"
# OPTS="--verbose"

PYTHONPATH="$SCRIPT_DIR"/code:"$PYTHONPATH" $PY "$SCRIPT_DIR"/code/wypp/runYourProgram.py \
    --no-clear $OPTS "$@"
exit $?
