#!/bin/bash

if [ -z "$PY" ]; then
    PY=python3
fi
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

OPTS="--quiet"
# OPTS="--verbose"

# For profiling, uncomment the line below
# PROF="-m cProfile -o profile.out"

$PY $PROF "$SCRIPT_DIR"/code/wypp/runYourProgram.py \
    --no-clear $OPTS "$@"
exit $?
