#!/bin/bash

PY=python3.13 
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

OPTS="--quiet"
# OPTS="--verbose"

PYTHONPATH="$SCRIPT_DIR"/site-lib:"$PYTHONPATH" $PY "$SCRIPT_DIR"/src/runYourProgram.py \
    --no-clear $OPTS "$@"
exit $?
