name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # You need to change to branch protection rules if you change the versions here
        python-version: [3.12.11, 3.13.7]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          cd python && ./allTestsForPyVersion
      - name: Test pytrace-generator
        run: |
          python3 python/src/runYourProgram.py --install-mode installOnly
          python3 pytrace-generator/test/runTests.py
