name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # You need to change to branch protection rules if you change the versions here
        python-version: [3.9.12, 3.9.16, 3.10.4, 3.10.9, 3.11.0, 3.11.1]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          cd python && ./allTestsForPyVersion
